webStoreFinal/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace webStoreFinal.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.pageName = "About Us";
            ViewBag.activeAbout = true;
            return View();
        }
    }
}

webStoreFinal/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using webStoreFinal.Models;
using webStoreFinal.Services;

namespace webStoreFinal.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ICartService _cartService;

        public ShoppingCartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        public IActionResult ShowCart()
        {
            ViewBag.pageName = "Current Cart Content";
            ViewBag.activeCart = true;
            List<Product> currentCart = _cartService.ShowCart();

            if(currentCart.Count==0)
            {
                ViewBag.emptyMsg = "You havn't any product in your shopping cart...for what are you waiting?";
            }
            else
            {
                double visitorPrice = _cartService.VisitorCartSum(currentCart);
                double memberPrice = _cartService.MemberCartSum(currentCart);

                TempData["visitorPrice"] = visitorPrice;
                TempData["memberPrice"] = memberPrice;
            }
            return View(currentCart);
        }

        public IActionResult RemoveFromCart(int id)
        {
            HashSet<int> cartProductsId = _cartService.RemoveProduct(id);
            return View("ShowCart", _cartService.ShowCart());

        }

        //gets the current item list storaged in cookies and updates it when an item is added
        //goes first to available items action
        [AllowAnonymous]
        public IActionResult AddToCart(int id, State productState)
        {
            if (productState == State.Available)
            {
                _cartService.AddProduct(id);
            }
            else
            {
                ViewBag.ErrorMessage = "sorry, the item is not availalbe at the moment";
            }
            return RedirectToAction("AvailableItems", "Home");

        }


        [HttpPost]//check if to do async
        public IActionResult CompletePurchase()
        {
            ViewBag.pageName = "Purchase Summary";
            _cartService.CompletePurchase();
            return View();
        }

    }
}

webStoreFinal/Views/Shared/_AdvertisePartialView.cshtml
@model Product
@inject IReadImage ReadImage


<head>
</head>
<body>
    <div class="border border-primary col-sm-3 col-lg-3 col-md-3">
        <div class="thumbnail">
            <h1 class="pull-right">@Model.Title </h1>
            @if (Model.Photo1 == null)
            {
                <img src="~/DefaultImage.png" class="defaultImage" />
            }
            else
            {
                <img src="@ReadImage.ByteToImage(Model.Photo1)" class="img-thumbnail" />
            }

        </div>
        <div class="caption">

            <h1 class="pull-right"> @Model.Price shekel</h1>
            <div class="pull-right">
                @Model.ShortDescription
            </div>
            <div>
                published date: @Model.PublishedDate
            </div>
            <div>
                @if (Model.Seller != null)
                {
                    <div>seller:@Model.Seller</div>
                }

            </div>

        </div>
        <a asp-action="AddToCart" asp-controller="ShoppingCart" asp-route-id=@Model.ProductKey asp-route-state=@Model.ProductState>
            <input type="button" value="Add To Cart" />
        </a>
        <a asp-action="ShowDetails" asp-controller="Home" asp-route-id="@Model.ProductKey">
            <input type="button" value="Show Details" />
        </a>
    </div>






</body>

webStoreFinal/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Layout";
}
@inject IHighlightActive HighlightServ

<head>

    <script src="~/jquery.js"></script>
    <script src="~/bootstrap.js"></script>
    <link href="~/bootstrap.css" rel="stylesheet" />
    <script src="~/popper.js"></script>
    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>



<body>
    <div class="alert alert-primary" role="alert">
        @if (IsSectionDefined("Title"))
        {
            @RenderSection("Title")
        }

    </div>

    <div class="log-in">
        @if (IsSectionDefined("login"))
        {
            RenderSection("Login");

        }

    </div>
    <div class="content">
        <nav class="navbar navbar-light bg-light fixed-left">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a asp-action="AvailableItems" asp-controller="home" class=@HighlightServ.classForNavLink(ViewBag.activeHome!=null)>Main Page</a>
                </li>
                <li class="nav-item">
                    <a asp-action="ShowCart" asp-controller="ShoppingCart" class=@HighlightServ.classForNavLink(ViewBag.activeCart!=null)>Shopping cart</a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Register" class=@HighlightServ.classForNavLink(ViewBag.activeRegister!=null)>Register</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">

                        <a asp-action="AddNewAdvertisement" asp-controller="home" class=@HighlightServ.classForNavLink(ViewBag.activeAdd!=null)>Add New Advertisement</a>
                        }

                    </li>
                }
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="About" class=@HighlightServ.classForNavLink(ViewBag.activeAbout!=null)>About</a>
                </li>

            </ul>
        </nav>
    </div>

    <div class="content">
        <div>
            @RenderBody()
        </div>
    </div>


</body>

webStoreFinal/Views/Shared/_LoginPartialView.cshtml
@model Login
@inject IUserRepository UserRepository
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@section Title{
    @await Html.PartialAsync("_TitlePartialView")
}

<div>
    @if (!User.Identity.IsAuthenticated)
    {
        <form asp-action="Login" asp-controller="Account" method="post">
            <div>
                <label asp-for="Username"></label>
                <input asp-for="Username" />

            </div>
            <div>
                <label asp-for="Password"></label>
                <input asp-for="Password" />
            </div>
            <div class="btn-group">
                <button type="submit" class="btn btn-primary btn-sm">Login</button>
                <button type="button" class="btn btn-danger btn-sm" asp-action="LogOut" asp-controller="Account">Log Out</button>

            </div>



        </form>
    }
    else
    {
        var userAuthenticated = await UserRepository.FindUserAuthAsync();

        <div class="alert-heading border-danger">
            @Html.TimeMessage();
            @userAuthenticated.FirstName  @userAuthenticated.LastName
        </div>
        <form asp-action="LogOut" asp-controller="Account">
            <button class="btn btn-danger btn-sm" >Log Out</button>
        </form>

    }
</div>

webStoreFinal/Views/Shared/_TitlePartialView.cshtml
<div class="title">
    <img class="logo" src="~/logo.png" alt="site logo" />
</div>


<div class="title">
    @ViewBag.pageName
</div>

webStoreFinal/Views/Shared/_WebLayout.cshtml
@{
    ViewData["Title"] = "webLayout";
}

<head>
    <link rel="stylesheet" href="~/StyleSheet.css" />

</head>

<body>
    <div class="top">
        @ViewBag.pageName
        <img src="pineapple.jpg" alt="Pineapple">
    </div>


    <div class="right-side">
        <div class="log-in">
            @if (IsSectionDefined("login"))
            {
                RenderSection("Login");
            }
            @if (IsSectionDefined("Greetings"))
            {
                RenderSection("Greetings");
            }
        </div>
        <nav class="nav-bar">
            <ul>
                <li><a asp-action="AvailableItems" asp-controller="home">Main Page</a></li>
                <li><a asp-action="ShowCart" asp-controller="ShoppingCart">Shopping cart</a></li>
                <li><a asp-action="Register" asp-controller="Rgister">Register</a></li>
                <li><a asp-action="Index" asp-controller="About">About</a></li>
            </ul>

        </nav>
    </div>
    <div class="left-side">
        @RenderBody()

    </div>
</body>